### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 7 quema del diablo in PowerShell Core

### ISSUE THREAD

**Issue by omiossec** [microsoft/25-days-of-serverless#201]
Please provide the following information for your submission:

### What is your name? (First, Last)
Olivier Miossec
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/omiossec/25-days-of-serverless-omc/tree/master/7-12
### What Challenge is this for? (Challenge number between 1 and 25)
7 
### (Optional) Anything else we should know? e.g., language used, location, blog post?
PowerShell, Paris (France), https://dev.to/omiossec

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @omiossec for creating this issue!

Have a Happy Holiday season!

**Comment by SandraAhlgrimm** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
