### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 7

### ISSUE THREAD

**Issue by Bhawk90** [microsoft/25-days-of-serverless#202]
Please provide the following information for your submission:

### What is your name? (First, Last)
Gabor Gulyas

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Bhawk90/25days-of-serverless/tree/master/day-7

### What Challenge is this for? (Challenge number between 1 and 25)
7

### (Optional) Anything else we should know? e.g., language used, location, blog post?
An "UnsplashAccessKey" and "UnsplashSecretKey" Environment variable is required to run the API and the endpoint only requires a "query" JSON Body parameter.
Used: Azure Functions (.NET Core), Unsplash Picture API

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @Bhawk90 for creating this issue!

Have a Happy Holiday season!

**Comment by SandraAhlgrimm** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
