### ISSUE TITLE
[CHALLENGE SUBMISSION] - Challenge7

### ISSUE THREAD

**Issue by FranzHelm** [microsoft/25-days-of-serverless#203]
Please provide the following information for your submission:

### What is your name? (First, Last)
Franz Helmberger

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/FranzHelm/hlc.25daysofserverless.chall7.git

### What Challenge is this for? (Challenge number between 1 and 25)
7

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @FranzHelm for creating this issue!

Have a Happy Holiday season!

**Comment by SandraAhlgrimm** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
