### ISSUE TITLE
[CHALLENGE SUBMISSION] 9

### ISSUE THREAD

**Issue by omiossec** [microsoft/25-days-of-serverless#225]
Please provide the following information for your submission:

### What is your name? (First, Last)
Olivier Miossec

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/omiossec/25-days-of-serverless-omc/tree/master/9-12

### What Challenge is this for? (Challenge number between 1 and 25)
9
### (Optional) Anything else we should know? e.g., language used, location, blog post?
PowerShell with Azure Functions (and a bit of GitHub Actions), Paris , https://dev.to/omiossec

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @omiossec for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
Thanks - Your README shows 2 good ways of solving this (both with github actions and powershell azure functions). I did not see the code in the repo - did I miss it?

**Comment by johnpapa** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
