### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 9

### ISSUE THREAD

**Issue by GeradeDev** [microsoft/25-days-of-serverless#228]
### What is your name? (First, Last)
Gerade Geldenhuys

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/GeradeDev/med-park-360/

### What Challenge is this for? (Challenge number between 1 and 25)
9

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Github Actions

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you @GeradeDev for creating this issue!

Have a Happy Holiday season!

**Comment by johnpapa** [comment]
Thanks - This is an awesome simple use of GitHub Actions!

Extra points for simplicity :)

**Comment by johnpapa** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
