### ISSUE TITLE
[CHALLENGE SUBMISSION]  - DAY 9

### ISSUE THREAD

**Issue by Je-ni** [microsoft/25-days-of-serverless#263]
Please provide the following information for your submission:

### What is your name? (First, Last)
Chidera Olibie

### Where is your GitHub Repo ?(With your challenge solution)
[ Click me for Solution](https://github.com/Je-ni/25DaysOfServerless/tree/master/day9)

### What Challenge is this for? (Challenge number between 1 and 25)
9

### (Optional) Anything else we should know? e.g., language used, location, blog post?
I used JavaScript (NodeJs) for this and the [article](https://dev.to/jeni/implement-serverless-text-sentiment-analysis-using-azure-text-analysis-api-kp) posted on dev.to I'm excited. My first submission :))

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by johnpapa** [comment]
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)

Thank you for your contributions! 

This issue is now resolved! 🎉
