### ISSUE TITLE
Typo in the wishes response

### ISSUE THREAD

**Issue by tugrulelmas** [microsoft/25-days-of-serverless#296]
**Versions (please complete the following information):**

- OS: mac

**Challenge**

- Week: 1
- Challenge: 5

**Describe the bug**
There is a typo in the wishes response. 

**To Reproduce**

1. Make a get request to https://christmaswishes.azurewebsites.net/api/Wishes
2. Find the 8th item
3. See the content of the item 
```
{
  "who": "jenifer",
  "mssage": "min lillasyster är jobbig"
}
```

**Expected behavior**
`mssage` should be `message`.

**Screenshots**
![image](https://user-images.githubusercontent.com/3829187/70827080-898cf500-1df9-11ea-9cd2-1217dcc50da6.png)

**Additional context**
N/A

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
Hi @tugrulelmas,
Thanks for letting us know and also for your eagle eyes!
 We will let Chris Noring know about this typo.
Cheers!
Jan
