### ISSUE TITLE
[CHALLENGE SUBMISSION] -day 13 - or something like that 😇

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/25-days-of-serverless#298]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Ba4bes/25daysofserverless/tree/master/Daya13GetaJoke

### What Challenge is this for? (Challenge number between 1 and 25)
13

### (Optional) Anything else we should know? e.g., language used, location, blog post?
I have changed the challenge a bit...
I was in no way able to complete the original challenge within a day. I have no experience with python. Or setting up Machine learning. I feel there was no way to work around this. Imho this challenge is a bit to specific.

So I made my own challenge, based on the real challenge. 
I have created a blob triggered function app that responses to the dataset-file that is uploaded.
It takes all the entries in the dataset and uses the Sentiment analysis service to give every joke a score  based on how nice it is. This is the base to work on and the jokes with their scores are stored in a CosmosDB.

When the tricksters want to get a joke, they can call on <https://4besday13.azurewebsites.net/api/GetJoke>.
This website will give one of the jokes that is in the top 25 of the highest scores in the database. 
The trickster can then rate if the joke is funny or not. If they enter that the joke isn't funny, the score is reduced by 0.1 points. If it is funny, it is increased by .1 points. The new data is written to the database.
So if enough tricksters use the joke-site, you should always get one of the 25 funniest jokes in the database.

Everything is of course running on PowerShell function apps, with CosmosDB. 
Not the original challenge, but I had a lot of fun anyway. And I wanted to at least have something to submit, to not break the streak :-)

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
I love your approach to this, @Ba4bes !

**Comment by jansche** [comment]
**THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION** 
We checked out your repository. We're thrilled to say your solution is now listed in our [Hall of Fame](https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md)
Thank you for your contributions! 
This issue is now resolved! 🎉
