### ISSUE TITLE
Challenge 15 , Broken Link for Quick Start

### ISSUE THREAD

**Issue by jayendranarumugam** [microsoft/25-days-of-serverless#322]
**Versions (please complete the following information):**

- OS: Windows, Chrome Browser

**Challenge**

- Week: 2
- Challenge: 15

**Describe the bug**
In the challenge, under the **Resource/Tools Used**  the link to **[Quickstart: Computer Vision client library for Java](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/)** is leads to 404 Not Found

**To Reproduce**

1. Go to 'https://25daysofserverless.com/calendar/15'
2. Click on 'Quickstart: Computer Vision client library for Java' Under **Resource/Tools Used**
3. See error as 404

**Expected behavior**
A valid link should be Opened

**Screenshots**
![image](https://user-images.githubusercontent.com/25414541/70884068-d986da00-1ffa-11ea-8a23-d34b6d440177.png)

![image](https://user-images.githubusercontent.com/25414541/70884046-ca079100-1ffa-11ea-8f47-3669a51d2921.png)

**Additional context**

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by SandraAhlgrimm** [comment]
Thank you for pointing that out! I was happy to solve that issue 🐱‍🏍
