### ISSUE TITLE
[CHALLENGE SUBMISSION] 16

### ISSUE THREAD

**Issue by nkelly75** [microsoft/25-days-of-serverless#329]
Please provide the following information for your submission:

### What is your name? (First, Last)
Niall Kelly

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/nkelly75/25-days-of-serverless/tree/master/day16

### What Challenge is this for? (Challenge number between 1 and 25)
16

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Simple node.js function, CI/CD with Azure DevOps, nice example of failing/passing tests - see [readme](https://github.com/nkelly75/25-days-of-serverless/blob/master/day16/README.md) for screenshots from Azure Pipelines.

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by trallard** [comment]
<table>
  <tr>
    <td><img src='https://image.flaticon.com/icons/png/512/2285/2285410.png' alt="Pinata Icon made by https://www.flaticon.com/authors/freepik"  width='50'/></th>
    <td><b>THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION</b><br>We checked your repository and we're thrilled to say your solution is now listed in our Hall of Fame.<br>Thank you for your contributions!</th>
  </tr>
</table>

--- 

This issue is now resolved! 🎉 🙌🏼
