### ISSUE TITLE
Challenge 2: Invalid Resources link

### ISSUE THREAD

**Issue by CEOehis** [microsoft/25-days-of-serverless#331]
**Versions (please complete the following information):**

- OS: Windows, Chrome Browser

**Challenge**

- Week: 1
- Challenge: 2

**Describe the bug**
In the challenge, under **Resources** the links to both "Logic App with Scheduling in the Azure Portal" and "Twillo" points to the same URL: https://azure.microsoft.com/en-us/services/scheduler/?WT.mc_id=25daysofserverless-github-cxa

**To Reproduce**

1. Go to https://25daysofserverless.com/calendar/2
2. Scroll to the **Resources** section
3. Open both links in new tabs
4. They both point to the same URL

**Expected behavior**
A different link should open for the Twilio link

**Screenshots**
<img width="1680" alt="Screenshot 2019-12-17 at 09 05 21" src="https://user-images.githubusercontent.com/25967737/70976829-f1b73180-20ac-11ea-8c25-b8a3ce9b7639.png">

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
Thanks @CEOehis, 
I've created a pull request and hopefully this is resolved with the next merge.
This helped a lot, thanks for your eagle eyes! I will close this issue now.
Cheers
Jan
