### ISSUE TITLE
[CHALLENGE SUBMISSION] How To Submit Solution with Logic Apps

### ISSUE THREAD

**Issue by mandardhikari** [microsoft/25-days-of-serverless#332]
Please provide the following information for your submission:

### (Optional) Anything else we should know? e.g., language used, location, blog post?
What artefact should I push to GIT repo for a logic apps solution?

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jlooper** [comment]
hi, for a Logic App, I believe you could submit a video or screenshot of your solution, and push the .yaml file, if I recall properly.

**Comment by jansche** [comment]
Hi @mandardhikari,
I've seen you've submitted an issue for this challenge, so I will close this issue. Thanks for asking!
Cheers
Jan
