### ISSUE TITLE
[CHALLENGE SUBMISSION] day 17

### ISSUE THREAD

**Issue by Ba4bes** [microsoft/25-days-of-serverless#333]
Please provide the following information for your submission:

### What is your name? (First, Last)
Barbara Forbes
### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/Ba4bes/25daysofserverless/tree/master/Daya17BBQontheBeach
### What Challenge is this for? (Challenge number between 1 and 25)
17
### (Optional) Anything else we should know? e.g., language used, location, blog post?
PowerShell Function App with Azure IOT Hub.

Didn't want to create a developers account in Twitter (or have time to wait for that), so I made an output to Teams instead. 
(If I wanted to send out a tweet, I would have used a logic app though, seems easier :) )

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)
