### ISSUE TITLE
[CHALLENGE SUBMISSION] 

### ISSUE THREAD

**Issue by mandardhikari** [microsoft/25-days-of-serverless#337]
Please provide the following information for your submission:

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Used Logic Apps and Event Grid To Create a serverless no code solution to tweet when the temperature rises above 31 degree Celsius. Attached is the word document detailing the solution and proof that the solution works.
[25DaysOfServerless-Day17SolutionWithLogicApps.docx](https://github.com/microsoft/25-days-of-serverless/files/3975594/25DaysOfServerless-Day17SolutionWithLogicApps.docx)

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by jansche** [comment]
Hi @mandardhikari,
would you mind putting the document in a repo with your account? You can also put images in the README.md file. That's how it works best for others submitting a solution. And you're still the owner of your files and able to take them offline if necessary.
In CONTRIBUTORS.md file, I prefer to link to people's repos and not link to the current location of your file.
You can then update this issue or create a new one.
Thanks in advance! 
Jan

**Comment by mandardhikari** [comment]
Following is the link to the Git Hub repo which contains the solution document.

https://github.com/mandardhikari/DaysOfServerless/blob/master/Day17/SolutionWIthLogicApps.md

**Comment by jansche** [comment]
<table>
  <tr>
    <td><img src='https://image.flaticon.com/icons/png/512/2285/2285410.png' alt="Pinata Icon made by https://www.flaticon.com/authors/freepik"  width='50'/></th>
    <td><b>THANK YOU FOR YOUR #25DaysOfServerless SUBMISSION</b><br>We checked your repository and we're thrilled to say your solution is now listed in our <a href="https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md" target="_blank"> Hall of Fame</a>.<br>Thank you for your contributions!</th>
  </tr>
</table>

--- 

This issue is now resolved! 🎉 🙌🏼
