### ISSUE TITLE
[CHALLENGE SUBMISSION] 18

### ISSUE THREAD

**Issue by jayendranarumugam** [microsoft/25-days-of-serverless#340]
Please provide the following information for your submission:

### What is your name? (First, Last)
Jayendran Arumugam

### Where is your GitHub Repo ?(With your challenge solution)
https://github.com/jayendranarumugam/25daysofserverless/tree/master/ComputervisionCh18.functions

### What Challenge is this for? (Challenge number between 1 and 25)
18

### (Optional) Anything else we should know? e.g., language used, location, blog post?
Azure Functions with Java, Computer Vision, Blob Trigger

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)
