### ISSUE TITLE
[CHALLENGE SUBMISSION] Challenge 18

### ISSUE THREAD

**Issue by mandardhikari** [microsoft/25-days-of-serverless#341]
Please provide the following information for your submission:

### Where is your GitHub Repo ?
https://github.com/mandardhikari/25DaysOfServerlessChallange18

### (Optional) Anything else we should know? e.g., language used, location, blog post?
The solution discusses two approaches to trigger azure functions, one using event grid and another using Blob Trigger

**Comment by johnpapa** [comment]
From all of us on the Cloud Advocacy team at Microsoft, thank you for creating this issue!
    

Have a Happy Holiday season!
    

Feel free to [share your solution on Twitter with the tag #25DaysOfServerless](https://twitter.com/intent/tweet?text=%2325DaysOfServerless)

**Comment by brminnick** [comment]
Congratulations Mandar! 

Your submission has been selected as the best submission for the Day 18 Challenge! 🎉 🎉 🎉 

Thank you so much for joining us for 25 Days of Serverless 🙌 

https://github.com/microsoft/25-days-of-serverless/blob/master/CONTRIBUTORS.md#week-three---challenge-18
