### ISSUE TITLE
Future challenges are accessible

### ISSUE THREAD

**Issue by JohnPhamous** [microsoft/25-days-of-serverless#39]
Not sure if this was intended but the future challenges are accessible by navigating to their URL.

`https://25daysofserverless.com/calendar/${n}`

**Comment by glaucia86** [comment]
Hi @JohnPhamous! Thank you so much for warning us. I'll include this issue as bugfix to @christiannwamba and @simonaco 

Thank you very much!

**Comment by christiannwamba** [comment]
Thanks @JohnPhamous 

Sent a PR for this and should be in production asap

**Comment by christiannwamba** [comment]
Fixed:

1. https://25daysofserverless.com/calendar/3 -- 401 friendly error
2. https://25daysofserverless.com/calendar/2 -- Challenge content

Thanks for catching this @JohnPhamous
