### ISSUE TITLE
25daysofserverless.com NOT accessible

### ISSUE THREAD

**Issue by oliverwhk** [microsoft/25-days-of-serverless#392]
I'm trying to catch up on the challenges but now the page are not accessible. It's saying "Please wait till the due date to start a challenge." which may be it got the year wrong :(

https://25daysofserverless.com/calendar/4

**Comment by johnpapa** [comment]
The unthinkable has happened: after weeks of community members all over the globe chipping in to help solve people's problems with serverless technology, the evil grinch's heart is starting to soften! He's still not quite ready to give up his server-stealing plot, but our whole Azure Cloud Advocacy team is flying up to the grinch's lair to help convince him to change his ways.


As such, the team behind 25 Days of Serverless is OOF (Out Of Facility/Office) between Dec 24, 2019 and January 1, 2020. We'll not review Issues in this period of time, but encourage you to catch up on any challenges you haven't had the time to work on yet. 😄 Our [Discord Server](https://discord.gg/8kbAeud) is a perfect place to reach out to for community support during this time. After our return, we'll add contributors who submitted a working solution as an Issue to CONTRIBUTORS.md file until January 15, 2020.

**Comment by Ba4bes** [comment]
Don't have the resolution, but a bit of a workaround: I have copied and pasted every assignment in my repository. If you go to https://github.com/Ba4bes/25daysofserverless there is a readme in every folder where you can find the challenge of that day. It is the bare challenge though, it is missing the helpful links. But at least you will be able to keep going for now

**Comment by stuartleaver** [comment]
@oliverwhk Just to add to the reply from Ba4bes, it seems that I was still copying the links at Day 4. I did stop at some point though.

https://github.com/stuartleaver/25-days-of-serverless/tree/master/04-api-endpoint

**Comment by jansche** [comment]
Hey y'all, I apologize for the inconveniences. Just returned to my desk after vacation, and already escalated this issue. 
We'll fix it asap.

**Comment by christiannwamba** [comment]
Fixed this now and closing the issue. Feel free to reopen if you still run into a problem related to this

**Comment by jakubsuchybio** [comment]
Yeah I saved this 25day challenge for later reading, later just came, but the web is again down :(
![image](https://user-images.githubusercontent.com/6567287/167305593-9ce7e665-caaa-472f-b97f-a0f3cbd36d9a.png)
