### ISSUE TITLE
The link to Twillio is incorrect

### ISSUE THREAD

**Issue by mattleibow** [microsoft/25-days-of-serverless#71]
https://github.com/microsoft/25-days-of-serverless/blob/master/week-1/challenge-2/README.md

**Comment by glaucia86** [comment]
Thank you for warning us @mattleibow .

Resolved it.

**Comment by mattleibow** [comment]
There is also the case in the Resources section: https://github.com/microsoft/25-days-of-serverless/blob/master/week-1/challenge-2/README.md#resources-
