### ISSUE TITLE
Submission issue template is not a PR template

### ISSUE THREAD

**Issue by mattleibow** [microsoft/25-days-of-serverless#72]
I missed the template when creating a new PR for my submission as it was an issue template.

I am not sure why the PR template is not appearing - I see you have a file for that.

**Comment by mattleibow** [comment]
Just had a look and is see the ISSUE template for the submission is different to the PR template. Not sure which is the correct one to use.

**Comment by glaucia86** [comment]
Hi @mattleibow!

We included here right now: https://github.com/microsoft/25-days-of-serverless/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

Thank you!
